name: Python Flask Docker Build

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cleanup
      run: |
        docker stop flask || true
        docker rm flask || true
        docker image prune -af || true

    - name: Build Docker Image
      run: |
        imageName="python/flask:${GITHUB_RUN_NUMBER}"
        docker build -t $imageName .

    - name: Run Docker Container
      run: |
        docker run --name flask -d -p 5000:5000 python/flask:${GITHUB_RUN_NUMBER}

    - name: Delete Previous Build Image
      run: |
        previousBuildNumber=$((GITHUB_RUN_NUMBER-1))
        previousImageName="python/flask:${previousBuildNumber}"
        docker image rm $previousImageName || true
